appKom/ravioli

src/components/Events/Event.jsx

Endret fra .thumb- til .xs-bilde

Bedre oppløsning på event-bilder

---

src/App.jsx
src/components/Badge.jsx

51 badge komponent

---

src/components/AppInsideProvider.jsx
src/components/Badge.jsx
src/components/EventCard.jsx
src/components/EventCarousel.jsx
src/lib/date.js
src/lib/eventTypes.js

La til:
- Ny badge med farge som viser type arrangement
- "Tekstboble" som viser antall plasser igjen
- Setning under arrangementer som forklarer hvor man melder seg på
- Litt større tekst i badge-komponenten

Mer farger

---

src/components/EventCard.jsx

Bruker event.ingress istedenfor event.description siden jeg tror dette passer bedre for infoskjermen.
Korta også ned på litt kode i samme fil.

Bytt ut description med ingress

---

src/components/EventCard.jsx

Viser på hvert påmeldingsarrangement enten:
- Frist utløp
- Ingen plasser
- x på venteliste
- x plasser igjen

Viser antall på venteliste

---

src/components/EventCard.jsx

Hvis påmelding ikke har åpnet viser det nå hvor mange dager/timer/minutter til påmelding åpner.

Vise tid til påmelding åpner

---

.eslintrc.js
src/App.tsx
src/components/Badge.tsx
src/components/DarkModeContainer.tsx
src/components/Error.tsx
src/components/EventCard.tsx
src/components/EventCarousel.tsx
src/components/Header.tsx
src/components/Loading.tsx
src/components/Logo/BekkLogo.tsx
src/components/Logo/OnlineLogo.tsx
src/components/SeasonalGraphic.jsx
src/index.tsx

Don't need to import React in all component files, so changed the eslint config and removed them all.

Removed all react imports

---

src/lib/messages.ts

Added more cute messages such as valentinsday, woman's day and 17.may in messages.ts

Added more cute messages

---

src/components/DarkModeContainer.tsx

Fixed a bug where it checked for darkmode only every 8 hours. Now it fetches the latest sunrise/sundown times every 8 hours, but check up against these values every minute.

Fix check darkmode every minute

---

src/components/cards/MemeCard.tsx

"Oops, her skjedde det en feil :(" i meme-kortet hvis bildet ikke ble lastet inn.

Showing an error message in each meme card if meme image fails to load

---

src/lib/date.ts

- Fikset feil hvor det sto "1 dager siden".
- Refaktorerte funksjonen så det er lettere å lese

formatSlackDate() viser "1 dag" istedenfor "1 dager"

---

package-lock.json
package.json
src/components/cards/BlastCard.tsx
src/components/cards/MemeCard.tsx

Endringer:
- Første linje i meldingen er større og bold
- De resterende linjene er maks 4 linjer høye
- Hvis de meldingen går over 4 linjer, vises "Les resten på #korktavla"
- Gjorde profilbildene litt større (måtte også endre i MemeCard, så profilbildene matcher:) )
Før:
Etter:

Endret BlastCard

---

src/App.tsx
src/components/utils/Error.tsx
src/components/utils/Loading.tsx

Lagde to lister for error- og feilmeldinger. Blir valgt en random melding fra listene.

114 error & loading messages

---

src/App.tsx

Var en bug som gjorde at blasts på slack siden hakket noen ganger.

Fikset slack hakke bug?

---

src/App.tsx
src/components/Header.tsx

For å gjøre det lettere under utvikling har jeg gjort det mulig å endre side manuelt ved å trykke på sirkelen øverst til høyre.

Gjort det mulig å bytte side manuelt

---

src/App.tsx
src/components/Videopage.tsx

Implementert et videokomponent for infoskjermen, hvor den tar en liste med ulike videoer fra yt i tilfeldig rekkefølge.

31 Implementert videokomponent for infoskjermen

---

src/components/cards/BlastCard.tsx
src/components/cards/EventCard.tsx
src/lib/text.ts

Removed special characters in event text. Also moved some of the text formatting functions in the same lib-file.
Before:
After:

Fixed event card text formatting

---

src/App.tsx
src/components/header/Header.tsx
src/components/pages/VideoPage.tsx

The page change is now based on probability, not iterative. Also added the option to change the display time of each page.
Can be customized in the `pages`-array:

New way to switch pages based on probabilities

---

src/components/header/Header.tsx
src/components/utils/DarkModeProvider.tsx

Now possible to toggle dark mode by pressing the logo/clock.

Toggle darkmode manually

---

backend/src/text.ts

Viser nå kanal-navnet istedenfor kanal-koden når man referer til slack-kanaler

Turn channel links text into actual channel name

---

frontend/src/lib/text.ts

Fix indent quote stuff on slack messages

---

backend/src/media.ts
frontend/src/components/Badge.tsx
frontend/src/components/cards/BlastCard.tsx
frontend/src/components/cards/EventCard.tsx
frontend/src/components/cards/MemeCard.tsx
frontend/src/lib/types.ts

Added channel name in badge

---

frontend/src/components/pages/MainPage.tsx

Er altfor vanlig sånn det er nå.
Jeg så den sånn tre ganger mens jeg satt på A4-138 nå i sted.

Update Brat Frequency

---

frontend/src/components/LatestBlasts.tsx
frontend/src/components/LatestMemes.tsx
frontend/src/components/skeletons/BlastCardSkeleton.tsx
frontend/src/components/skeletons/MemeCardSkeleton.tsx

Added skelton loaders to slack page

---

frontend/src/components/pages/ChristmasPage.tsx

Bigger christmas countdown

---

backend/index.ts
backend/vercel.json
frontend/src/components/pages/MainPage.tsx

Fixed vercel settings to point to new cron-endpoint, and added schedule to run the cronjob once every hour from 7AM to 9PM

Added cron endpoint, and changed schedule

---

backend/src/channelsConfig.ts

Added more slack channels to `blasts`

Added #utveksling and #kontoret

---

frontend/src/components/VideoComponent.tsx
frontend/src/components/cards/MemeCard.tsx
frontend/src/lib/useIsVisible.tsx

Hopefully fixes videos taking forever to load on nibble.
https://dev.to/mattlewandowski93/lazy-loaded-video-component-in-react-22dp

Lazy loaded video component

---

frontend/src/components/pages/EasterPage.tsx

Endret på max width and height

Adjusting chicken size

---

frontend/src/components/pages/MainPage.tsx

Added support for disabling the header and making single pages fullscreen. This will be nice on the Jubkom page for example

Add support for fullscreen pages

---

frontend/src/components/pages/CharityPage.tsx

Added blæst about onlove.no

---

frontend/src/api/owApi.ts
frontend/src/components/cards/EventCard.tsx
frontend/src/components/pages/EventsPage.tsx
frontend/src/lib/event.ts
frontend/src/lib/types.ts
frontend/vite.config.ts

90% ferdig, trenger småjusteringer. Se slack for mer info

275 update old ow to new
